# vim: ft=yaml.docker-compose
name: komodo

include:
  - path:
      - ext/docker-compose-snippets/caddy.yaml
      - ext/docker-compose-snippets/reverse_proxy_override.yaml
services:
  mongo:
    image: mongo
    depends_on:
      tailscale:
        condition: service_healthy
    network_mode: service:tailscale
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25 --bind_ip 127.0.0.1
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    restart: unless-stopped
  core:
    image: ghcr.io/mbecker20/komodo:latest
    hostname: proxy_target
    depends_on:
      tailscale:
        condition: service_started
      mongo:
        condition: service_started
    network_mode: service:tailscale
    labels:
      komodo.skip:
    environment:
      KOMODO_TITLE: Komodo
      KOMODO_HOST: https://komodo.ipn.rahulsalvi.com
      KOMODO_BIND_IP: "127.0.0.1"
      KOMDOO_PORT: 9120
      KOMODO_PASSKEY: ${KOMODO_PASSKEY}
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
      KOMODO_LOCAL_AUTH: true
      KOMODO_DATABASE_ADDRESS: localhost:27017
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - repo-cache:/repo-cache
    restart: unless-stopped
volumes:
  mongo-data:
  mongo-config:
  repo-cache:
secrets:
  ts_authkey:
    file: ./ts_authkey.txt
